seed: 159753

device: cuda
debug: true
gen_freq: 5

compile: true

model:
  d_model: 128
  n_layers: 2
  n_heads: 4
  d_ff: 256
  dropout: 0.0

diffusion:
  timesteps: 500  
  K: 27
  ce_coeff: 0.1

trainer:
  batch_size: 256
  min_lr: 1e-6
  max_lr: 2e-3
  warmup_steps: 200
  epochs: 5
  max_steps: 20000
  log_freq: 50
  num_workers: 2

data:
  root: data/text8
  seq_len: 256

sample:
  size: 32