seed: 159753
device: cuda

compile: true

diffusion:
  timesteps: 1000
  K: 16
  ce_coeff: 0.001

trainer:
  batch_size: 64
  min_lr: 1e-6
  max_lr: 5e-4
  warmup_steps: 45000
  epochs: 2000
  max_steps: 400000
  log_freq: 100
  accumulation_steps: 2
  num_workers: 4
  optim_name: adamw

data:
  root: data/
  img_size: 32
  dataset: "cifar10"
  download: false

sample:
  size: 32